tap "github/gh"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

# Install GNU core utilities (those that come with macOS are outdated)
brew "coreutils"

# GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew "findutils"

# For handy tools like "chronic" and "parallel"
brew "moreutils"

brew "ack"
brew "autoconf"
brew "cloc"
brew "cmake"
brew "dnsmasq"
brew "dockutil"
brew "ffmpeg"
brew "gcc"
brew "gh"
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "gnupg"
brew "gnutls"
brew "grep"
brew "haproxy"
brew "id3lib"
brew "krb5"
brew "ldns"
brew "libfido2"
brew "libxml2"
brew "mas"
brew "memcached"
brew "ncdu"
brew "nmap"
brew "nvm"
brew "openssh"
brew "postgresql"
brew "pyenv"
brew "ruby-build"
brew "rbenv"
brew "redis"
brew "rename"
brew "screen"
brew "srt"
brew "tldr"
brew "tmux"
brew "trash"
brew "tree"
brew "vim"
brew "watch"
brew "watchman"
brew "wget"
brew "wxmac"
brew "yarn"
brew "youtube-dl"
brew "heroku/brew/heroku"

cask "android-studio"
cask "appcleaner"
cask "chromedriver"
cask "cyberduck"
cask "docker"
cask "dropbox"
cask "evernote"
cask "firefox"
cask "google-chrome"
cask "insomnia"
cask "iterm2"
cask "keepingyouawake"
cask "licecap"
cask "macdown"
cask "mysqlworkbench"
cask "selfcontrol"
cask "sequel-pro"
cask "sketch"
cask "slack"
cask "tableplus"
cask "tuple"
cask "vagrant"
cask "virtualbox"
cask "viscosity"
cask "visual-studio-code"
cask "xquartz"
cask "zoom"

# non-dev/work apps I may want
# cask "arduino"
# cask "balenaetcher"
# cask "garmin-basecamp"
# cask "google-earth-pro"
# cask "handbrake"
# cask "vlc"
# cask "prusaslicer"
# cask "spotify"

# App Store packages
mas "ColorSlurp", id: 1287239339
mas "Navicat Essentials for PostgreSQL", id: 466725643
# mas "Xcode", id: 497799835
