sudo: true
language: node_js
node_js:
  - "6"
  - "5"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - curl https://raw.githubusercontent.com/twolfson/sublime-installer/0.1.3/install.sh | sh -s 3
  - subl --version
before_script:
  - npm install -g gulp-cli
  - npm i
script: gulp
